// data.jsx — mock data for BeautyHub for Masters

const ICONS = {
  search: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-3-3"/></svg>',
  arrow: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>',
  arrowL: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 12H5m6 6-6-6 6-6"/></svg>',
  star: '<svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><path d="m12 2 3 7 7 .6-5.3 4.6 1.6 6.8L12 17l-6.3 4 1.6-6.8L2 9.6 9 9z"/></svg>',
  pin: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 21s-7-7.5-7-12a7 7 0 0 1 14 0c0 4.5-7 12-7 12z"/><circle cx="12" cy="9" r="2.5"/></svg>',
  clock: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
  user: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c1-4 4-6 8-6s7 2 8 6"/></svg>',
  check: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 5 5L20 7"/></svg>',
  filter: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 5h18M6 12h12M10 19h4"/></svg>',
  bolt: '<svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M13 2 4 14h7l-1 8 9-12h-7z"/></svg>',
  cam: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="6" width="18" height="14" rx="2"/><circle cx="12" cy="13" r="4"/></svg>',
  fan: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 12c0-4 2-7 5-7s5 3 0 7M12 12c4 0 7 2 7 5s-3 5-7 0M12 12c0 4-2 7-5 7s-5-3 0-7M12 12c-4 0-7-2-7-5s3-5 7 0"/></svg>',
  sink: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 12h18l-2 8H5z"/><path d="M9 12V6a3 3 0 0 1 6 0"/></svg>',
  lamp: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 2h6l3 7H6zM12 9v9M9 21h6"/></svg>',
  mirror: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><ellipse cx="12" cy="9" rx="6" ry="7"/><path d="M12 16v6M9 22h6"/></svg>',
  plug: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 2v6M15 2v6M6 8h12v4a6 6 0 0 1-12 0zM12 18v4"/></svg>',
  wifi: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 9a16 16 0 0 1 20 0M5 13a11 11 0 0 1 14 0M8.5 16.5a6 6 0 0 1 7 0"/><circle cx="12" cy="20" r="1" fill="currentColor"/></svg>',
  coffee: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 8h13v6a5 5 0 0 1-10 0z M16 10h2a3 3 0 0 1 0 6h-2 M5 2v3M9 2v3M13 2v3"/></svg>',
  park: '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M9 7h4a3 3 0 0 1 0 6H9zM9 13v4"/></svg>',
};

const SERVICE_TYPES = [
  { id: 'all',     label: 'Все',          count: 18 },
  { id: 'nails',   label: 'Маникюр',      count: 6 },
  { id: 'hair',    label: 'Парикмахер',   count: 4 },
  { id: 'brows',   label: 'Бровист',      count: 3 },
  { id: 'lash',    label: 'Лэшмейкер',    count: 2 },
  { id: 'makeup',  label: 'Визажист',     count: 2 },
  { id: 'massage', label: 'Массаж',       count: 1 },
  { id: 'cosmo',   label: 'Косметолог',   count: 2 },
  { id: 'pmu',     label: 'Перманент',    count: 1 },
];

const DURATIONS = [
  { id: 'h1', label: '1 час' },
  { id: 'h2', label: '2 часа' },
  { id: 'h4', label: '4 часа' },
  { id: 'shift', label: 'Смена' },
  { id: 'day', label: 'День' },
];

const EQUIPMENT = [
  { id: 'fan',    label: 'Вытяжка',      icon: 'fan' },
  { id: 'sink',   label: 'Мойка',        icon: 'sink' },
  { id: 'lamp',   label: 'LED-лампа',    icon: 'lamp' },
  { id: 'mirror', label: 'Зеркало с подсветкой', icon: 'mirror' },
  { id: 'plug',   label: '4+ розетки',   icon: 'plug' },
  { id: 'wifi',   label: 'Wi-Fi',        icon: 'wifi' },
];

const ROOM_TYPES = [
  { id: 'open', label: 'Open space' },
  { id: 'cab',  label: 'Кабинет' },
];

const SPACES = [
  {
    id: 'N-04',
    code: 'N-04',
    type: 'nails',
    typeLabel: 'Нейл-зона',
    title: 'Нейл-стол №4',
    room: 'open',
    roomLabel: 'Open space',
    floor: 1,
    price: 12,
    priceUnit: '₽/час',
    rating: 4.9,
    reviews: 142,
    bookings: 312,
    available: 14,
    busy: 0.4,
    badge: 'Топ выбор',
    badgeKind: 'accent',
    equip: ['fan', 'lamp', 'plug', 'wifi'],
    photos: ['Стол + лампа', 'Вытяжка', 'Кресло клиента', 'Общий план'],
  },
  {
    id: 'N-02',
    code: 'N-02',
    type: 'nails',
    typeLabel: 'Нейл-зона',
    title: 'Нейл-стол №2',
    room: 'open',
    roomLabel: 'Open space',
    floor: 1,
    price: 10,
    priceUnit: '₽/час',
    rating: 4.8,
    reviews: 98,
    bookings: 240,
    available: 9,
    busy: 0.6,
    equip: ['fan', 'lamp', 'plug'],
    photos: ['Стол', 'Лампа', 'Вид сверху', 'Окно'],
  },
  {
    id: 'H-01',
    code: 'H-01',
    type: 'hair',
    typeLabel: 'Парикмахер',
    title: 'Парикмахерское кресло №1',
    room: 'open',
    roomLabel: 'Open space',
    floor: 1,
    price: 15,
    priceUnit: '₽/час',
    rating: 5.0,
    reviews: 76,
    bookings: 198,
    available: 6,
    busy: 0.7,
    badge: 'Color bar',
    badgeKind: 'ok',
    equip: ['sink', 'mirror', 'plug', 'wifi'],
    photos: ['Кресло + зеркало', 'Color bar', 'Мойка', 'Общий план'],
  },
  {
    id: 'H-02',
    code: 'H-02',
    type: 'hair',
    typeLabel: 'Парикмахер',
    title: 'Парикмахерское кресло №2',
    room: 'open',
    roomLabel: 'Open space',
    floor: 1,
    price: 14,
    priceUnit: '₽/час',
    rating: 4.7,
    reviews: 54,
    bookings: 121,
    available: 11,
    busy: 0.3,
    equip: ['sink', 'mirror', 'plug'],
    photos: ['Кресло', 'Свет', 'Мойка'],
  },
  {
    id: 'M-01',
    code: 'M-01',
    type: 'makeup',
    typeLabel: 'Визажист',
    title: 'Визаж-кресло у окна',
    room: 'open',
    roomLabel: 'Open space',
    floor: 2,
    price: 13,
    priceUnit: '₽/час',
    rating: 4.9,
    reviews: 64,
    bookings: 152,
    available: 8,
    busy: 0.5,
    badge: 'Дневной свет',
    badgeKind: 'default',
    equip: ['mirror', 'lamp', 'plug', 'wifi'],
    photos: ['Кресло у окна', 'Кольцевой свет', 'Зеркало', 'Палитра'],
  },
  {
    id: 'B-01',
    code: 'B-01',
    type: 'brows',
    typeLabel: 'Бровист',
    title: 'Бровист — кресло №1',
    room: 'open',
    roomLabel: 'Open space',
    floor: 2,
    price: 11,
    priceUnit: '₽/час',
    rating: 4.8,
    reviews: 41,
    bookings: 89,
    available: 12,
    busy: 0.35,
    equip: ['lamp', 'mirror', 'plug'],
    photos: ['Кресло', 'Лампа', 'Стол', 'Стеллаж'],
  },
  {
    id: 'L-01',
    code: 'L-01',
    type: 'lash',
    typeLabel: 'Лэшмейкер',
    title: 'Кабинет лэшмейкера',
    room: 'cab',
    roomLabel: 'Кабинет',
    floor: 2,
    price: 18,
    priceUnit: '₽/час',
    rating: 5.0,
    reviews: 88,
    bookings: 174,
    available: 5,
    busy: 0.75,
    badge: 'Изолированно',
    badgeKind: 'accent',
    equip: ['lamp', 'plug', 'wifi'],
    photos: ['Кушетка', 'Лампа', 'Хранение', 'Свет'],
  },
  {
    id: 'C-01',
    code: 'C-01',
    type: 'cosmo',
    typeLabel: 'Косметолог',
    title: 'Кабинет косметолога',
    room: 'cab',
    roomLabel: 'Кабинет',
    floor: 2,
    price: 22,
    priceUnit: '₽/час',
    rating: 4.9,
    reviews: 52,
    bookings: 98,
    available: 7,
    busy: 0.55,
    equip: ['sink', 'lamp', 'plug', 'wifi'],
    photos: ['Кушетка', 'Раковина', 'Аппарат', 'Полки'],
  },
];

const TIMES = ['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00'];

const TARIFFS = [
  {
    id: 'hour',
    name: 'Почасовая',
    price: '12',
    unit: '₽ / час',
    desc: 'Платите только за нужные часы. Минимум — 1 час.',
    perks: ['Бронь от 1 часа', 'Все расходники', 'Wi-Fi и кофе', 'Отмена за 24ч'],
    cta: 'Забронировать час',
    highlight: false,
  },
  {
    id: 'shift',
    name: 'Смена',
    price: '85',
    unit: '₽ / 8 часов',
    desc: 'Полный день за фиксированную цену. -12% к почасовой.',
    perks: ['8 часов подряд', 'Приоритет на топ-зоны', 'Бесплатная парковка', 'Гибкая отмена'],
    cta: 'Взять смену',
    highlight: true,
    save: '−12%',
  },
  {
    id: 'month',
    name: 'Подписка',
    price: '1 280',
    unit: '₽ / месяц',
    desc: '20 смен в месяц с закреплённой зоной. -28% к почасовой.',
    perks: ['Закреплённая зона', '20 смен / месяц', 'Профиль на витрине', 'Доступ к событиям'],
    cta: 'Оформить подписку',
    highlight: false,
    save: '−28%',
  },
];

const EVENTS = [
  { date: '14 МАЯ', type: 'Мастер-класс', title: 'Архитектура брови 2026', host: 'Анна Костюк', price: '120 ₽', seats: 8 },
  { date: '21 МАЯ', type: 'Воркшоп',     title: 'Color bar: палитра сезона', host: 'Kevin.Murphy', price: '95 ₽',  seats: 12 },
  { date: '28 МАЯ', type: 'Открытый день', title: 'Day pass для нейл-мастеров', host: 'BeautyHub', price: 'free', seats: 20 },
  { date: '04 ИЮН', type: 'Курс',         title: 'Перманент: техника пудры', host: 'Diana M.', price: '480 ₽', seats: 6 },
];

const FACTS = [
  { num: '120+', label: 'мастеров каждый месяц' },
  { num: '8',    label: 'рабочих зон' },
  { num: '24/7', label: 'доступ по подписке' },
  { num: '4.9',  label: 'средний рейтинг' },
];

const FAQ = [
  { q: 'Как происходит бронирование?', a: 'Выбираете зону, дату и слот. Оплата картой онлайн. На входе — QR-доступ.' },
  { q: 'Что входит в стоимость?', a: 'Рабочее место, расходники, кофе и вода, Wi-Fi, парковка, фотозона, поддержка администратора.' },
  { q: 'Можно ли отменить бронь?', a: 'Да, бесплатно — не позднее, чем за 24 часа до начала. После — удерживается 50%.' },
  { q: 'Нужны ли свои инструменты?', a: 'Базовые расходники есть. Личные инструменты приветствуются — для гигиены и комфорта.' },
];

const BENEFITS = [
  { num: '01', title: 'Платите только за работу', text: 'Никакой аренды салона на месяц. Час, смена или подписка — на ваш выбор.' },
  { num: '02', title: 'Готовое оборудование',     text: 'Лампы, мойки, вытяжки, color bar. Всё стерильно, всё работает.' },
  { num: '03', title: 'Витрина клиентам',         text: 'Профиль мастера на сайте BeautyHub. Бронирования идут к вам напрямую.' },
  { num: '04', title: 'Сообщество и обучение',    text: 'Мастер-классы, открытые дни, обмен клиентами между мастерами.' },
];

window.BH = { ICONS, SERVICE_TYPES, DURATIONS, EQUIPMENT, ROOM_TYPES, SPACES, TIMES, TARIFFS, EVENTS, FACTS, FAQ, BENEFITS };
